export type Package = {
  speed: number;
  name: string;
  description?: string;
  devices: number;
  badge?: string | null;
  price: number;
  package_group: string;
  addons: string[];
  benefits: string[];
};

export const INDIHOMES = [
  // Paket 1P (Internet)
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    badge: "Paling Populer",
    price: 265_000,
    package_group: "Paket 1P (Internet)",
    addons: [],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
    ],
  },
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    badge: null,
    price: 295_000,
    package_group: "Paket 1P (Internet)",
    addons: ["disney-hotstar"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
    ],
  },
  {
    speed: 30,
    name: "IndiHome Movie 1P 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    badge: "Penawaran Terbaik",
    price: 379_000,
    package_group: "Paket 1P (Internet)",
    addons: ["indihome-tv", "disney-hotstar", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
    ],
  },
  {
    speed: 50,
    name: "Paket Digital JITU 1 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    badge: "Paling Populer",
    price: 325_000,
    package_group: "Paket 1P (Internet)",
    addons: ["indihome-tv", "disney-hotstar"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
    ],
  },
  {
    speed: 50,
    name: "Paket Dynamic 1P 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    badge: "Paling Untung",
    price: 370_000,
    package_group: "Paket 1P (Internet)",
    addons: ["indihome-tv", "disney-hotstar", "maxstream"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Kuota keluarga 15GB untuk 6 nomor",
      "30 menit voice & 30 SMS seluruh operator",
      "Unlimited voice & SMS sesama member",
    ],
  },
  {
    speed: 100,
    name: "Paket Digital JITU 1 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    badge: "Paling Untung",
    price: 395_000,
    package_group: "Paket 1P (Internet)",
    addons: ["indihome-tv", "disney-hotstar"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
    ],
  },
  {
    speed: 50,
    name: "IndiHome Movie 1P 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 399_000,
    package_group: "Paket 1P (Internet)",
    addons: ["indihome-tv", "disney-hotstar", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
    ],
  },
  {
    speed: 50,
    name: "Paket Complete 1P 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    badge: "Penawaran Terbaik",
    price: 405_000,
    package_group: "Paket 1P (Internet)",
    addons: [],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Kuota keluarga 15GB untuk 6 nomor",
      "30 menit voice & 30 SMS seluruh operator",
      "Unlimited voice & SMS sesama member",
      "Kuota Orbit 20 GB (belum termasuk modem Orbit Rp 425.000)",
    ],
  },
  {
    speed: 100,
    name: "Paket Complete 1P 50 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 449_000,
    package_group: "Paket 1P (Internet)",
    addons: ["indihome-tv", "disney-hotstar", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
    ],
  },
  {
    speed: 100,
    name: "Paket Dynamic 1P 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 480_000,
    package_group: "Paket 1P (Internet)",
    addons: ["indihome-tv", "disney-hotstar", "maxstream"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Kuota keluarga 15GB untuk 6 nomor",
      "30 menit voice & 30 SMS seluruh operator",
      "Unlimited voice & SMS sesama member",
    ],
  },
  {
    speed: 100,
    name: "Paket Complete 1P 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 515_000,
    package_group: "Paket 1P (Internet)",
    addons: [],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Kuota keluarga 15GB untuk 6 nomor",
      "30 menit voice & 30 SMS seluruh operator",
      "Unlimited voice & SMS sesama member",
      "Kuota Orbit 20 GB (belum termasuk modem Orbit Rp 425.000)",
    ],
  },
  {
    speed: 300,
    name: "Paket Complete 1P 100 Mbps",
    description: "Cocok digunakan untuk maks 20 perangkat",
    devices: 20,
    price: 888_000,
    package_group: "Paket 1P (Internet)",
    addons: ["indihome-tv", "disney-hotstar", "maxstream"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Kuota keluarga 15GB untuk 6 nomor",
      "30 menit voice & 30 SMS seluruh operator",
      "Unlimited voice & SMS sesama member",
    ],
  },
  // Paket 2P (Internet+TV)
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 320_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: [],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
    ],
  },
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 340_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: ["indihome-tv", "disney-hotstar"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
    ],
  },
  {
    speed: 30,
    name: "Paket IndiHome Netflix 2P-TV 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 365_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: ["indihome-tv", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>28 Channel</span>",
    ],
  },
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 370_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: ["indihome-tv"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Minipack Big Combo <span class='text-red-500'>List Channel</span>",
    ],
  },
  {
    speed: 30,
    name: "Paket IndiHome Netflix 2P-TV 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 385_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: ["indihome-tv", "disney-hotstar", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>28 Channel</span>",
    ],
  },
  {
    speed: 30,
    name: "Paket IndiHome Gamer 2P-TV 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 399_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: ["indihome-tv", "gameqoo"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>28 Channel</span>",
    ],
  },
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 455_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: [
      "indihome-tv",
      "catchplay-plus",
      "vidio",
      "disney-hotstar",
      "wetv-iflix",
    ],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Minipack Big Combo <span class='text-red-500'>List Channel</span>",
    ],
  },
  {
    speed: 50,
    name: "Paket IndiHome Netflix 2P-TV 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 460_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: ["indihome-tv", "disney-hotstar", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Paket TV <span class='text-red-500'>28 Channel</span>",
    ],
  },
  {
    speed: 50,
    name: "Paket Digital JITU 1 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 505_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: ["indihome-tv", "catchplay-plus", "disney-hotstar", "wetv-iflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
    ],
  },
  {
    speed: 50,
    name: "Paket Digital JITU 1 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 505_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: [
      "indihome-tv",
      "catchplay-plus",
      "vidio",
      "disney-hotstar",
      "wetv-iflix",
    ],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Minipack Big Combo <span class='text-red-500'>List Channel</span>",
    ],
  },
  {
    speed: 100,
    name: "Paket Digital JITU 1 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 530_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: ["indihome-tv", "catchplay-plus", "disney-hotstar", "wetv-iflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
    ],
  },
  {
    speed: 100,
    name: "Paket IndiHome Netflix 2P-TV 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 555_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: ["indihome-tv", "disney-hotstar", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Paket TV <span class='text-red-500'>28 Channel</span>",
    ],
  },
  {
    speed: 50,
    name: "Paket Complete 2P 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 555_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: [
      "indihome-tv",
      "catchplay-plus",
      "vidio",
      "disney-hotstar",
      "mola",
      "wetv-iflix",
      "maxstream",
    ],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Kuota keluarga 15GB untuk 6 nomor",
      "30 menit voice & 30 SMS seluruh operator",
      "Unlimited voice & SMS sesama member",
      "Kuota Orbit 20 GB (belum termasuk modem Orbit Rp 425.000)",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
    ],
  },
  {
    speed: 100,
    name: "Paket Complete 2P 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 730_000,
    package_group: "Paket 2P (Internet+TV)",
    addons: [
      "indihome-tv",
      "catchplay-plus",
      "vidio",
      "disney-hotstar",
      "mola",
      "wetv-iflix",
      "maxstream",
    ],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Kuota keluarga 15GB untuk 6 nomor",
      "30 menit voice & 30 SMS seluruh operator",
      "Unlimited voice & SMS sesama member",
      "Kuota Orbit 20 GB (belum termasuk modem Orbit Rp 425.000)",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
    ],
  },
  // Paket 2P (Internet+Phone)
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 285_000,
    package_group: "Paket 2P (Internet+Phone)",
    addons: [],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 300_000,
    package_group: "Paket 2P (Internet+Phone)",
    addons: ["disney-hotstar"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 30,
    name: "Paket IndiHome Gamer 2P-Phone 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 375_000,
    package_group: "Paket 2P (Internet+Phone)",
    addons: ["gameqoo"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 50,
    name: "Paket Digital JITU 1 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 350_000,
    package_group: "Paket 2P (Internet+Phone)",
    addons: ["indihome-tv", "disney-hotstar"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 100,
    name: "Paket Digital JITU 1 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 410_000,
    package_group: "Paket 2P (Internet+Phone)",
    addons: ["indihome-tv", "disney-hotstar"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 50,
    name: "Paket IndiHome Gamer 2P-Phone 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 545_000,
    package_group: "Paket 2P (Internet+Phone)",
    addons: ["disney-hotstar", "gameqoo", "pijar-belajar", "langit-musik"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 100,
    name: "Paket IndiHome Gamer 2P-Phone 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 895_000,
    package_group: "Paket 2P (Internet+Phone)",
    addons: ["disney-hotstar", "gameqoo", "pijar-belajar", "langit-musik"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Telepon Rumah 100 Menit",
    ],
  },
  // Paket 3P (Internet+TV+Phone)
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 340_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: [],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 360_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: ["indihome-tv", "disney-hotstar"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 390_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: ["indihome-tv"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Minipack Big Combo <span class='text-red-500'>List Channel</span>",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 30,
    name: "Paket IndiHome Netflix 3P 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 410_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: ["indihome-tv", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Telepon Rumah 50 Menit",
    ],
  },
  {
    speed: 30,
    name: "Paket IndiHome Netflix 3P 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 430_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: ["indihome-tv", "disney-hotstar", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Telepon Rumah 50 Menit",
    ],
  },
  {
    speed: 30,
    name: "Paket Digital JITU 1 30 Mbps",
    description: "Cocok digunakan untuk maks 3 perangkat",
    devices: 3,
    price: 475_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: [
      "indihome-tv",
      "catchplay-plus",
      "vidio",
      "disney-hotstar",
      "wetv-iflix",
    ],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 30 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Minipack Big Combo <span class='text-red-500'>List Channel</span>",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 50,
    name: "Paket Digital JITU 1 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 495_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: ["indihome-tv", "catchplay-plus", "disney-hotstar", "wetv-iflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 50,
    name: "Paket IndiHome Netflix 3P 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 505_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: ["indihome-tv", "disney-hotstar", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 50,
    name: "Paket Digital JITU 1 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 515_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: [
      "indihome-tv",
      "catchplay-plus",
      "vidio",
      "disney-hotstar",
      "wetv-iflix",
    ],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Minipack Big Combo <span class='text-red-500'>List Channel</span>",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 100,
    name: "Paket Digital JITU 1 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 550_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: ["indihome-tv", "catchplay-plus", "disney-hotstar", "wetv-iflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 100,
    name: "Paket IndiHome Netflix 3P 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 590_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: ["indihome-tv", "disney-hotstar", "netflix"],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
    ],
  },
  {
    speed: 50,
    name: "Paket IndiHome Gamer 3P 50 Mbps",
    description: "Cocok digunakan untuk maks 5 perangkat",
    devices: 5,
    price: 615_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: [
      "indihome-tv",
      "disney-hotstar",
      "gameqoo",
      "pijar-belajar",
      "langit-musik",
    ],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 50 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Telepon Rumah 100 Menit",
    ],
  },
  {
    speed: 100,
    name: "Paket IndiHome Gamer 3P 100 Mbps",
    description: "Cocok digunakan untuk maks 10 perangkat",
    devices: 10,
    price: 965_000,
    package_group: "Paket 3P (Internet+TV+Phone)",
    addons: [
      "indihome-tv",
      "disney-hotstar",
      "gameqoo",
      "pijar-belajar",
      "langit-musik",
    ],
    benefits: [
      "Bebas biaya pasang (Normal Rp500.000)",
      "Kecepatan internet hingga 100 Mbps",
      "Paket TV <span class='text-red-500'>81 Channel</span>",
      "Telepon Rumah 100 Menit",
    ],
  },
];

export default INDIHOMES;
